version: "3.4"

services:
  rabbitmq-server:
    build: .
    container_name: rabbitmq-server
    restart: always
    env_file:
      - .env
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - rabbitmq_data:/data
  rabbitmq-client:
    build: .
    container_name: rabbitmq-client
    restart: unless-stopped
    environment:
      - RABBITMQ_NODENAME=rabbit@rabbitmq-server
    volumes:
      - rabbitmq_data:/data

volumes:
  assets: {}
  rabbitmq_data:
    driver: local
